dist: xenial
language: node_js
matrix:
  include:
    - node_js: 8
    - node_js: 10
      env: UPLOAD_COVERAGE=true
    - node_js: 11
after_success:
  - if [[ "$UPLOAD_COVERAGE" = "true" ]]; then bash <(curl -s https://codecov.io/bash); fi
cache: npm
notifications:
  email:
    on_success: never
    on_failure: always
